version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: ./node_modules/ember-cli/bin/ember test

  deploy:
    docker:
      - image: circleci/node:8.7
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Deploy to GitHub Pages
          command: |
            git checkout gh-pages; git checkout master
            ./node_modules/ember-cli/bin/ember deploy production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install
      - test
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
